package com.example.freshscan.domain.model

/**
 * AI-generated 7-day personalized diet plan.
 *
 * Generated by DietPlanEngine via Qwen API based on UserProfile.
 * Persisted as JSON columns in Room (diet_plans table).
 */
@Deprecated("Replaced by MealSuggestion for single-meal query approach")
data class DietPlan(
    val id: String,                          // UUID
    val generatedAt: Long,                   // Timestamp
    val userProfileSnapshot: UserProfile,    // Profile used at generation time
    val dailyPlans: List<DailyMealPlan>,     // 7 days (Mon–Sun)
    val totalCaloriesAvg: Int,               // Average daily calorie target
    val nutritionSummary: String             // AI-generated nutrition summary
)

@Deprecated("Replaced by MealSuggestion")
data class DailyMealPlan(
    val dayIndex: Int,          // 1-7
    val dayLabel: String,       // "周一" … "周日"
    val totalCalories: Int,
    val meals: List<Meal>,
    val notes: String? = null
)

@Deprecated("Replaced by MealSuggestion")
data class Meal(
    val type: MealType,
    val recipe: DietRecipe
)

enum class MealType(val label: String) {
    BREAKFAST("早餐"),
    LUNCH("午餐"),
    DINNER("晚餐"),
    SNACK("加餐")
}

/**
 * A recipe within a diet plan meal.
 *
 * Similar to [Recipe] but generated by AI rather than presets.
 * Ingredients use the existing [Ingredient] domain model for
 * shopping list compatibility.
 */
@Deprecated("Replaced by MealSuggestion")
data class DietRecipe(
    val title: String,
    val ingredients: List<Ingredient>,
    val steps: List<String>,         // 3-5 cooking steps
    val cookingTimeMin: Int,
    val calories: Int,
    val proteinG: Float,
    val carbsG: Float,
    val fatG: Float
)
