package com.example.freshscan.data.history

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for AI meal query history.
 *
 * Each row represents a single meal suggestion generated by the AI
 * in response to a user query. JSON columns store structured data
 * (ingredients, steps) to keep the schema simple.
 */
@Entity(tableName = "meal_history")
data class MealHistoryEntity(
    @PrimaryKey val id: String,
    val query: String,
    val title: String,
    val ingredientsJson: String,   // JSONArray of {"name":"...", "amount":"..."}
    val stepsJson: String,         // JSONArray of strings
    val cookingTimeMin: Int,
    val calories: Int,
    val proteinG: Double,
    val carbsG: Double,
    val fatG: Double,
    val generatedAt: Long
)
